ERROR:2024-01-10 20:09:00,982:Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\conda\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "f:\github\everything\u-can-see-everything-in-there\class\rand\main.py", line 97, in insert
    1/0
ZeroDivisionError: division by zero

ERROR:2024-01-10 20:09:51,403:Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\conda\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "f:\github\everything\u-can-see-everything-in-there\class\rand\main.py", line 97, in insert
    1/0
ZeroDivisionError: division by zero

INFO:2024-01-12 19:59:12,932: 周五18:30 永久增加 "coco"
